// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiweb.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(MyBirdAppDbContext))]
    [Migration("20240529114527_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apiweb.Model.ObservationsInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("chatId")
                        .HasColumnType("bigint");

                    b.Property<string>("comName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("howMany")
                        .HasColumnType("int");

                    b.Property<float>("lat")
                        .HasColumnType("real");

                    b.Property<float>("lng")
                        .HasColumnType("real");

                    b.Property<string>("locId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("locName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("locationPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("obsDt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("obsReviewed")
                        .HasColumnType("bit");

                    b.Property<bool>("obsValid")
                        .HasColumnType("bit");

                    b.Property<string>("sciName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("speciesCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OwnListOfObservationsInfo");
                });

            modelBuilder.Entity("apiweb.Model.RegionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegionsUkraie");
                });
#pragma warning restore 612, 618
        }
    }
}
